### ISSUE TITLE
Crash on comments in .env files

### ISSUE THREAD

**Issue by bennycode** [moveline/gulp-env#13]
I have a [.env](https://github.com/motdotla/dotenv) file which uses comments:

**.env**

```bash
# Here is a comment
DB_HOST=localhost
DB_USER=root
```

This leads to a crash when using `gulp-env` because it cannot parse comments:

```
[23:29:04] Using gulpfile D:\dev\projects\bennyn\mondlandung\gulpfile.js
[23:29:04] Starting 'set-env'...
[23:29:04] 'set-env' errored after 7.08 ms
[23:29:04] D:\dev\projects\bennyn\mondlandung\.env:1
(function (exports, require, module, __filename, __dirname) { # Here is a comment
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

```

**gulpfile.js**

```js
const env = require('gulp-env');
const gulp = require('gulp');

gulp.task('default', ['set-env'], () => {
  console.log('Hello World', process.env.NODE_DEBUG);
});

gulp.task('set-env', function () {
  env({
    file: '.env',
    vars: {
      FORCE_COLOR: 1,
      NODE_DEBUG: 'moon:*',
      NTBA_FIX_319: 1,
    }
  });
});
```

**Comment by bennycode** [comment]
It can be quickfixed by renaming `.env` into `.env.ini` or by specifying a `type`:

```js
gulp.task('set-env', function () {
  env({
    file: '.env',
    type: '.ini',
    vars: {
      FORCE_COLOR: 1,
      NODE_DEBUG: 'moon:*',
      NTBA_FIX_319: 1,
    }
  });
});
```

**Comment by DarkLite1** [comment]
Stumbled upon this same issue as I was using the following in the `package.json`:

`"dev": "nodemon -r dotenv/config ./src/index.js dotenv_config_path=./config/.env -e js,hbs,json,css",`

Had to add the `type`, although I think this should not be required as it works without type for `dotenv` too:

```js
env({
        file: './config/.env',
        type: '.ini'
})
```
